### PR TITLE
fix the data that displays for a listing

### PR DESCRIPTION
**Pull request by dlouise64**
# What has changed and why?
Show correct data for a listing
also fixed a lot of code climate errors

this PR should be merged first

# How to test this change

- [ ] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] tested in small screen
- [ ] i18n
- [ ] tested in screen reader/contrast <-- remove this if no UX change

### CODE REVIEW

**Comment by Br3nda** [comment]
display looks a bit wonky.

image

**Comment by Br3nda** [comment]
I'm seeing the same listings in every category.

image
image
image

**Comment by dlouise64** [comment]
@Br3nda All done now, have tested it too.

**Comment by Br3nda** [comment]
I've added categories to the spreadsheet so the app can filter

**Pull request merged**
